### ISSUE TITLE
Several client "fetch" functions returning None

### ISSUE THREAD

**Issue by theyaoster** [colinhartigan/valclient.py#9]
I've noticed that some of the functions are returning `None` - perhaps the API path has changed? Namely the following:

**_contracts_fetch_active_story
contracts_fetch_definitions
fetch_player_restrictions_**

I didn't check all the client functions though, these are just the ones I came across. I am only able to test in NA.

I've tried looking for updated documentation on these APIs - there's a few other github pages that came up, but none of them worked.

Steps to repro:

1. Run VALORANT.
2. Run the following:
```
from valclient import Client

client = Client(region="na")
client.activate()

print(client.contracts_fetch_active_story())
print(client.contracts_fetch_definitions())
print(client.fetch_player_restrictions())
```

**Comment by awsare** [comment]
I believe that they've changed from V2 to V3.
